In [12]:
import pandas as pd

df1 = pd.DataFrame({
    "id" : [1, 2, 3],
    "customer_id" : [1, 2, 3],
    "customer_name" : ["Rovert","Peter", "Jimmy"]
}, columns = ["id", "customer_id", "customer_name"])

In [30]:
import pandas as pd
df2 = pd.DataFrame({
    "id" : [1, 2, 4],
    "order_id" : [100, 200, 300],
    "order_date" : ["2025-01-01","2025-06-01", "2025-05-24"]
}, columns = ["id", "order_id", "order_date"])

In [ ]:
# 서로 다른 데이터 프레임을 하나로 합치는 방법

1) concat() : 서로 다른 데이터 프레임을 단순 연결 (*교차되는 특정 인덱스 고려X) -> 좌, 우 & 상, 하 (디폴트)
2) merge() : 특정 인덱스를 기준

In [5]:
pd.concat([df1, df2])

   id  customer_id customer_name  order_id
0   1          1.0        Rovert       NaN
1   2          2.0         Peter       NaN
2   3          3.0         Jimmy       NaN
0   1          NaN           NaN     100.0
1   2          NaN           NaN     200.0
2   4          NaN           NaN     300.0

In [6]:
doc = pd.concat([df1, df2], axis=1)
doc

   id  customer_id customer_name  id  order_id customer_name
0   1            1        Rovert   1       100           NaN
1   2            2         Peter   2       200           NaN
2   3            3         Jimmy   4       300           NaN

In [18]:
pd.merge(df1, df2) # merge() => inner JOIN과 유사

   id  customer_id customer_name  order_id  order_date
0   1            1        Rovert       100  2025-01-01
1   2            2         Peter       200  2025-06-01

In [19]:
pd.merge(df1,df2, on="id")

   id  customer_id customer_name  order_id  order_date
0   1            1        Rovert       100  2025-01-01
1   2            2         Peter       200  2025-06-01

In [23]:
pd.merge(df1, df2, on="id", how="outer")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Rovert     100.0  2025-01-01
1   2          2.0         Peter     200.0  2025-06-01
2   3          3.0         Jimmy       NaN         NaN
3   4          NaN           NaN     300.0  2025-05-24

In [24]:
pd.merge(df1, df2, on="id", how="left")

   id  customer_id customer_name  order_id  order_date
0   1            1        Rovert     100.0  2025-01-01
1   2            2         Peter     200.0  2025-06-01
2   3            3         Jimmy       NaN         NaN

In [25]:
pd.merge(df1, df2, on="id", how="right")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Rovert       100  2025-01-01
1   2          2.0         Peter       200  2025-06-01
2   4          NaN           NaN       300  2025-05-24

In [27]:
df1 = df1.set_index("id")
df1

    customer_id customer_name
id
1             1        Rovert
2             2         Peter
3             3         Jimmy

In [31]:
df2 = df2.set_index("id")
df2

    order_id  order_date
id
1        100  2025-01-01
2        200  2025-06-01
4        300  2025-05-24

In [32]:
pd.merge(df1, df2, left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1             1        Rovert       100  2025-01-01
2             2         Peter       200  2025-06-01

In [33]:
pd.merge(df1, df2, how="outer", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Rovert     100.0  2025-01-01
2           2.0         Peter     200.0  2025-06-01
3           3.0         Jimmy       NaN         NaN
4           NaN           NaN     300.0  2025-05-24

In [34]:
pd.merge(df1, df2, how="left", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1             1        Rovert     100.0  2025-01-01
2             2         Peter     200.0  2025-06-01
3             3         Jimmy       NaN         NaN

In [35]:
pd.merge(df1, df2, how="right", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Rovert       100  2025-01-01
2           2.0         Peter       200  2025-06-01
4           NaN           NaN       300  2025-05-24

In [36]:
df = pd.DataFrame({
    "영어": [60, 70],
    "수학": [100, 50],
    "국어": [50, 80]
}, columns=["영어", "수학"], index=["Jimmy", "jim"])
df

       영어   수학
Jimmy  60  100
jim    70   50

In [ ]:
# def func(df_data) :
#     print(type(df_data))
#     print(df_data.index)
#     print(df_data.values)
def func(df_data) :
    df_data["영어"] = 80
    return df_data

In [ ]:
df_func = df.apply(func, axis=1)

In [ ]:
df_func = df.apply(func, axis=0)

In [ ]:
df_func

In [38]:
df = pd.DataFrame({
    "성별" : ["남","남","남"],
    "이름" : ["David","jimmy","jim"],
    "수학" : [100,50,80],
    "국어" : [80,70,50]
})

  성별     이름   수학  국어
0  남  David  100  80
1  남  jimmy   50  70
2  남    jim   80  50

In [42]:
selected_columns = ["이름", "수학", "국어"]

df = df[selected_columns]
df.groupby("이름").sum()

        수학  국어
이름
David  100  80
jim     80  50
jimmy   50  70

In [45]:
import os

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
file_list, csv_list = os.listdir(PATH), list()

FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/'